sudo: false
language: python

python:
  - '3.6'

script:
 - pytest

deploy:
  provider: pypi
  user: thestr4ng3r
  password:
    secure: cwyz5kvUk11rEDeSeInInbDy6QxERTexUZ/7sXRsXhw5GIBiY/NQTBSSWT0j8YHQW5os3N81hQZygu0fD8PxVQMplnSffMtKcwly2n3TAjI4iE+TTsJ6d1CABSRdB02SKcBDVAl1uT51m/nZADy9tn/Klj6uE2QCJUzHehWoBXXZtLNKiLcMy1dC0eFmefwM2kq+K1gV2Xmo4OikSya1SkBERswPxhnPZuUwWOpauOmRPeqiHODJFoJ/z2uKDunI8vFQpzVEEpOztuzhMAqlAgXgu0eNfKIvgJJxy+VN2roWGhNUJHZcnop3q1QqALg/Oz2iceMIM+Q7mqkg1vswStLwY8jvDchBs/UbnkSlglUw9NQ9pf4Ner89cO25vqfk+cXzBZbUre9E7s2YhasfMlqZ8pnjjrT7pRPQxpHkzLV0tC6YldfXJY/3jo/jPjb9WIlNsFZbSDQ5CWNvoRNXnamdJ7Q9lxg3xGMFVDw4Ix6v+WVi1r3cmrAR5rwO1X8x7vjNGKd4vMmUt8ioEFI2XbGalbjYGduaRwg2XN5sp+0EE9elNZO/t9caGdw7MgRHgXRBaLgWLLF9KvxFsgmTRbfALS5Kg9EWJKaN+zpD3QvwLTMXgxzbb1H4T58TRkkUT/68hRyVKr62lNT7jnBJJd3SYDdaLTravdxgRXTxYNI=
  on:
    tags: true
